# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Shawn Xiao
title: Data Scientist
email: zhmxiao@student.ubc.ca
website: https://xiaotojohn.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  xiaotojohn
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: real_zhanming.x_
linkedin_username: zhanmingxiao
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: unsplash
  icon: fa-brands fa-unsplash
  url: https://unsplash.com/@xiaotojohn
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Shawn and I'm a data scientist. I'm currently studying at the University of British Columbia and am looking for a job in the data science field. I have a passion for data analytics and photography and am always looking for new projects to work on.

  I am most skilled in: <mark>data analytics</mark> and <mark>photography</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/xiaotojohn/ml_proj
        # link_text: Project Website
        quote: >
          A project. It's super awesome. You should check it out.
        description: | # this will include new lines to allow paragraphs
          This project was super awesome. I did some stuff and it was great. You should check it out. It's on my GitHub.
    # content:
      - layout: top-middle
        title: Tableau Data Visualization Projects
        link: https://public.tableau.com/app/profile/zhanming.xiao/vizzes
        # link_text: Tableau Public Profile
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Some Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Business Analyst
        caption: November 2017 - Present
        quote: >
          making sure the whole company stays connected
        description: | # this will include new lines to allow paragraphs
            during my time at Some Company I did some stuff and it was great. You should check it out. It's on my GitHub.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of British Columbia
        caption: 2023-2024
        sub_title: Master of Business Analytics
        quote: >
          Gained proficiency in data-driven decision making
        description: | # this will include new lines to allow paragraphs
          Developed advanced skills in data analysis, statistical modeling, and machine learning applications for business solutions. 
          Gained hands-on experience in using tools such as Python, R, and SQL for data manipulation, predictive analytics, and business intelligence reporting. 
          Courses included data visualization, econometrics, and data-driven decision making in areas like marketing and finance. 
          Worked on projects involving real-world datasets to optimize business processes and create actionable insights for complex business problems.
      - layout: left
        title: University of Victoria
        caption: 2019-2022
        sub_title: Bachelor of Commerce
        quote: >
           Acquired a comprehensive foundation in business and management
        description: | # this will include new lines to allow paragraphs
          Studied key aspects of business management including finance, marketing, operations, and organizational behavior. 
          Developed skills in strategic thinking, business planning, and market analysis. 
          Gained exposure to accounting principles, financial reporting, and risk management. 
          Participated in group projects simulating real-world business challenges, focusing on leadership, teamwork, and problem-solving. 
          Completed internships that provided practical experience in business operations and strategy development.

      - layout: left
        title: Shanghaitech University
        caption: 2015-2018
        sub_title: Computer Science
        quote: >
          Acquired a solid foundation in computer science and programming.
        description: | # this will include new lines to allow paragraphs
          Developed strong skills in algorithms, data structures, and software engineering principles. 
          Gained proficiency in multiple programming languages, including Python, Java, and C++. 
          Engaged in courses covering computer architecture, operating systems, and database management. 
          Worked on capstone projects involving software development, data analysis, and system optimization. 
          Participated in coding competitions and collaborated on open-source projects, gaining practical exposure to collaborative software development.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Check my photography out on [Unsplash](https://unsplash.com/@xiaotojohn).
      They are all free to use and I would love to see them in action.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
