# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Shawn Xiao
title: Data Analyst/Full Stack Developer/Tutor/Business Advisor/Photographer
email: zhmxiao@student.ubc.ca
website: https://xiaotojohn.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  xiaotojohn
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: real_zhanming.x_
linkedin_username: zhanmingxiao
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: unsplash
  icon: fa-brands fa-unsplash
  url: https://unsplash.com/@xiaotojohn
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hey there, glad you stopped by! I'm Shawn, someone with an insatiable curiosity about nearly everything in the universe.
  - I've lived in two countries, five cities, and have explored diverse fields like computer science and commerce along the way.
  - I've been active in Toastmasters, taking on leadership roles like area director and club president. I've also dabbled in several professional roles, including educational consultant, developer, business development officer, due diligence advisor, and research assistant. And yes, I tutor physics and math too!
  - I love working with both people and machines, finding that balance between the two. I'm also a big fan of reading history and imagining how humanity might evolve to shape the universe (which is why I like Foucault and Asimov).
  But if you're wondering what I excel at most, here it is:
  <mark>Data Analytics, Business Consulting, and Education.</mark>
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Machine Learning Projects
        link: github.com/xiaotojohn/ml_proj
    # content:
      - layout: top-middle
        title: Tableau Data Visualization Projects
        link: https://public.tableau.com/app/profile/zhanming.xiao/vizzes
        # link_text: Tableau Public Profile
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Global Nexus Education Inc.
        link: https://globalnexusgroup.com/
        sub_title: Business Development Officer
        caption: October 2022 – December 2023
        quote: >
          Driving business growth through strategic process improvement
        description: |
          Collaborated with key stakeholders in a dynamic start-up environment to identify and secure business expansion opportunities. 
          Spearheaded the development and execution of project initiatives, including the creation of an innovative summer camp program for high school students abroad. 
          My role spanned across marketing, product design, budget planning, and operational procedures, resulting in a 20% increase in organizational efficiency.
  
      - layout: left
        title: University of Victoria
        sub_title: Research Assistant for Inclusive Community of Older Immigrants
        caption: July 2022 – August 2023
        quote: >
          Researching social isolation and community integration
        description: |
          Provided strategic support in a multi-year research project aimed at reducing social isolation among senior immigrants. 
          Designed and implemented data collection methodologies, and conducted in-depth analysis to identify key demographic patterns. 
          This work significantly enhanced the project's ability to design effective interventions for improving community engagement and well-being.
  
      - layout: left
        title: Dajia Insurance Group Co. Ltd
        sub_title: Internship
        caption: September 2021 – December 2021
        quote: >
          Supporting financial data analysis and reporting
        description: |
          Consolidated financial data and generated key financial reports for asset management and client portfolios. 
          Assisted in virtual business meetings, translation, and administrative functions that supported the finance department's overall operations.
  
      - layout: left
        title: Tangram Culture Academy
        sub_title: Instructor
        caption: January 2021 – Present
        quote: >
          Empowering students in AP and post-secondary level courses
        description: |
          Instructed K-12 students in advanced placement courses such as AP Calculus, AP Statistics, and AP Physics. 
          Utilized adaptive teaching methods to maximize academic performance and ensure student success in rigorous subjects.
  
      - layout: left
        title: Vancouver Public Education Alliance
        sub_title: Higher Education Consultant
        caption: January 2021 – September 2021
        quote: >
          Guiding students towards their academic aspirations
        description: |
          Delivered expert consulting services, offering comprehensive career planning and educational guidance tailored to students' goals. 
          Provided support to international students, assisting them with academic assignments, daily life challenges, and mental health resources.
  
      - layout: left
        title: Toastmasters International
        sub_title: Area Director
        caption: July 2023 – Present
        quote: >
          Leading communication excellence
        description: |
          Steered the strategic growth and operational success of multiple Toastmasters clubs. 
          Fostered a culture of effective communication and leadership while ensuring high membership engagement and educational outcomes.
  
  

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of British Columbia
        caption: 2023-2024
        sub_title: Master of Business Analytics
        quote: >
          Gained proficiency in data-driven decision making
        description: | # this will include new lines to allow paragraphs
          Developed advanced skills in data analysis, statistical modeling, and machine learning applications for business solutions. 
          Gained hands-on experience in using tools such as Python, R, and SQL for data manipulation, predictive analytics, and business intelligence reporting. 
          Courses included data visualization, econometrics, and data-driven decision making in areas like marketing and finance. 
          Worked on projects involving real-world datasets to optimize business processes and create actionable insights for complex business problems.
      - layout: left
        title: University of Victoria
        caption: 2019-2022
        sub_title: Bachelor of Commerce
        quote: >
           Acquired a comprehensive foundation in business and management
        description: | # this will include new lines to allow paragraphs
          Studied key aspects of business management including finance, marketing, operations, and organizational behavior. 
          Developed skills in strategic thinking, business planning, and market analysis. 
          Gained exposure to accounting principles, financial reporting, and risk management. 
          Participated in group projects simulating real-world business challenges, focusing on leadership, teamwork, and problem-solving. 
          Completed internships that provided practical experience in business operations and strategy development.

      - layout: left
        title: Shanghaitech University
        caption: 2015-2018
        sub_title: Computer Science
        quote: >
          Acquired a solid foundation in computer science and programming.
        description: | # this will include new lines to allow paragraphs
          Developed strong skills in algorithms, data structures, and software engineering principles. 
          Gained proficiency in multiple programming languages, including Python, Java, and C++. 
          Engaged in courses covering computer architecture, operating systems, and database management. 
          Worked on capstone projects involving software development, data analysis, and system optimization. 
          Participated in coding competitions and collaborated on open-source projects, gaining practical exposure to collaborative software development.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Check my photography out on [Unsplash](https://unsplash.com/@xiaotojohn).
      They are all free to use and I would love to see them in action.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
